### ISSUE TITLE
Need step by step guide on how to use Obfuscar on Xamarin.Android projects

### ISSUE THREAD

**Issue by lextm** [obfuscar/docs#1]
We have an example for .NET Framework projects,

https://github.com/lextm/obfuscar_docs/blob/master/tutorials/basics.rst

Need step by step guide (or a sample project) for Xamarin.Android projects.

**Comment by lextm** [comment]
Related to https://github.com/obfuscar/obfuscar/issues/97

**Comment by wolfgangschneider** [comment]
Link is does not work, but would be helpful

**Comment by breyed** [comment]
The [Obfuscar home page](https://www.obfuscar.com/) specifically promotes Xamarin and mobile platforms as supported. Without an example or instructions, the support's practicality is limited.
