### ISSUE TITLE
.\Subfolder  specification $(OutPath)

### ISSUE THREAD

**Issue by frunta** [obfuscar/docs#2]
Dears,

   is there a way, how to process whole folder structure using **one** XML configuration file (preserving the structure)?

For instance 
```
<Obfuscator>
  <Var name="InPath" value=".\MyApp\bin\Release" />
  <Var name="OutPath" value="\Build" />

  <Module file="$(InPath)\MyApp.exe" />
  <Module file="$(InPath)\SubDir\plugin1.dll" />
  <Module file="$(InPath)\SubDir\Plugin2.dll" />
</Obfuscator>
```

with

```
 .\Build\MyApp.exe
 .\Build\SubDir\plugin1.dll
 .\Build\SubDir\plugin2.dll
```
as a result.
Thanks a lot!
Frunta.

**Comment by lextm** [comment]
You might keep multiple configuration files, while sharing common fragment file(s) among them,

http://docs.obfuscar.com/en/latest/getting-started/configuration.html#configuration-fragments-2-2-5
