### ISSUE TITLE
Unable to resolve dependency:  Xamarin.Forms.Core

### ISSUE THREAD

**Issue by shweta5tech** [obfuscar/docs#4]
While trying to Obfuscate Xamarin .Net standard 2.0 Projects dll's it is throwing with Below Exception:

Loading assemblies...Extra framework folders:
An error occurred during processing:
Unable to resolve dependency:  Xamarin.Forms.Core

Any idea how to solve this issue?

**Comment by lextm** [comment]
As that assembly is not copied to the output folder, you have to add a assembly search path,

http://docs.obfuscar.com/getting-started/configuration.html#assembly-search-path-2-2-5

and point to the folder that contains this assembly.

For example, on macOS that folder is `/Users/<user>/.nuget/packages/xamarin.forms/<version>/lib/netstandard2.0`.

**Comment by SteveSmith16384** [comment]
In your example, is there a way to refer to it regardless of who the user is, or if the config file is used on a different PC (i.e. with different users)?
