### ISSUE TITLE
Docs: please add how to use SkipEnums

### ISSUE THREAD

**Issue by brinkdinges** [obfuscar/docs#9]
Could you add a short example to [this](http://docs.obfuscar.com/getting-started/configuration.html) page in the documentation on how to use SkipEnums? It took me way too long to figure out that I needed to use:

`<SkipEnums value="true"/>`

Thanks in advance.

**Comment by FedericoNembrini** [comment]
I agree, I tried `<SkipEnums value="true"/>` but it's not working and from the documentation I don't understand how to make it work.

**Comment by lextm** [comment]
Most features were developed with corresponding test cases, so you can review them for hints,

https://github.com/obfuscar/obfuscar/blob/2.2.30/Tests/SkipEnumTests.cs
